services: docker

language: php
php:
  - 7.2

before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo service mysql stop

install:
  - make start

script:
  - make test

branches:
  only:
    - master
