version: '3'

services:

  db:
    image: mariadb:10
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=drupal
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    restart: always

  drupal:
    image: drupal:8-apache
    depends_on:
      - db
      - browser
    working_dir: /behat
    volumes:
      - webdata:/var/www/html
      - .:/behat
    ports:
      - 8080:80
    restart: always

  drush:
    image: drush/drush:8-alpine
    depends_on:
      - drupal
    volumes:
      - webdata:/var/www/html:rw,nocopy

  browser:
    image: selenium/standalone-firefox:3.4
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
    restart: always

volumes:
  webdata:
  dbdata:
